apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress-prod
type: Opaque
data:
  root-password: cm9vdHBhc3M=      # base64 for rootpass
  user: d3B1c2Vy                  # base64 for wpuser
  password: d3BwYXNz              # base64 for wppass
