apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init
  namespace: wordpress-prod
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'wpuser'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
    GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'%';
    FLUSH PRIVILEGES;
